# Generated by Django 4.1.5 on 2023-01-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=30)),
                ('recipe_image', models.ImageField(default='null.jpg', upload_to='SampleImage')),
                ('instruction', models.TextField()),
                ('ingredients', models.TextField()),
            ],
        ),
    ]
